services:
  nginx:
    container_name: rainbowtext_proxy
    depends_on:
      - server
    image: ****-2.amazonaws.com/rainbowtext_nginx
    logging:
      driver: awslogs
      options:
        awslogs-group: rainbowtext
        awslogs-region: us-west-2
        awslogs-stream-prefix: rainbowtext-nginx
    ports:
      - 80:80
  server:
    container_name: rainbowtext_server
    image: ******.amazonaws.com/rainbowtext_server
    logging:
      driver: awslogs
      options:
        awslogs-group: rainbowtext
        awslogs-region: us-west-2
        awslogs-stream-prefix: rainbowtext-server
    restart: always
version: '3'
